development:
  adapter: postgresql
  encoding: utf8
  database: looksee_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: looksee_test
  pool: 5
  
production:
  adapter: postgresql
  encoding: utf8
  database: looksee_production
  pool: 5
